In [0]:
import numpy as np

 Q1

In [0]:
a=np.array([1,2,3,2,3,4,3,4,5,6])

In [0]:
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [4]:
x=len(a)
for i in range(x):
 if a[i]==b[i]:
  print(i)





1
3
5
7


# Q2

In [0]:
a=np.array([2,6,1,9,10,3,27])

In [6]:
k=len(a)
k

7

In [7]:
for i in range(k): 
 if  4<a[i]<11:
  print(a[i])

6
9
10


# Q3

In [8]:
arr = np.arange(9).reshape(3,3)

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
t=arr[:,[1,]]
arr[:,[1,]]=arr[:,[2,]]
arr[:,[2,]]=t

In [10]:
arr

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

# Q4

In [11]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
arr[0]=np.flip(arr[0])
arr[1]=np.flip(arr[1])
arr[2]=np.flip(arr[2])

In [13]:
arr

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# Q5

In [14]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

sepalLength=iris_2d[:,0]
# This is the sepalLength
sepalLength

array([5.1, 4.9, nan, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, nan, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , nan, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, nan, 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [15]:
len(sepalLength)

150

In [0]:
#sp=sepalLength.sort()
#sp


In [17]:
print("the 5th percentile of iris's sepallength is ",sepalLength[4])
print("the 95th percentile of iris's sepallength is ",sepalLength[94])

the 5th percentile of iris's sepallength is  5.0
the 95th percentile of iris's sepallength is  5.6


# Q6

In [0]:
for i in range(len(sepalLength)):
  if sepalLength[i]=='nan':
   sepalLength[i]=0


In [22]:
sepalLength

array([5.1, 4.9, nan, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, nan, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , nan, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, nan, 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [23]:
np.isnan(sepalLength)

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

# Q8

In [24]:
arr=np.random.randint(23,78, size=9).reshape(3,3)
arr

array([[65, 32, 34],
       [29, 44, 42],
       [69, 47, 41]])

In [25]:
k=arr.flatten()
k.sort()
k

array([29, 32, 34, 41, 42, 44, 47, 65, 69])

In [26]:
print("The 2nd largest value is ",k[-2])

The 2nd largest value is  65


# Q9

In [27]:
arr=np.random.randint(1,78, size=9).reshape(3,3)
arr

array([[24, 15, 21],
       [63, 28, 68],
       [53, 38, 52]])

In [0]:
arr[arr>30]=30
arr[arr<10]=10

In [29]:
arr

array([[24, 15, 21],
       [30, 28, 30],
       [30, 30, 30]])

# Q10

In [30]:
arr=np.array([1,2,3,np.nan,5,6,7,np.nan])
arr

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan])

In [0]:
r= arr[np.logical_not(np.isnan(arr))]

In [32]:
r

array([1., 2., 3., 5., 6., 7.])