In [61]:
import numpy as np

In [62]:
arr1=np.arange(20).reshape(4,5)
arr1
arr=arr1

In [63]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing

In [64]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [65]:
t=arr[:,[0,]]
arr[:,[0,]]=arr[:,[3,]]
arr[:,[3,]]=t
arr

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

In [66]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row

In [67]:
arr1[0]=np.flip(arr1[0])
arr1[1]=np.flip(arr1[1])
arr1[2]=np.flip(arr1[2])
arr1[3]=np.flip(arr1[3])
arr1

array([[ 4,  0,  2,  1,  3],
       [ 9,  5,  7,  6,  8],
       [14, 10, 12, 11, 13],
       [19, 15, 17, 16, 18]])

In [77]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [69]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2

In [79]:
col_mean = np.nanmean(arr2, axis=0)

inds = np.where(np.isnan(arr2))

arr2[inds] = np.take(col_mean, inds[1])

print(arr2)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [2.5 3.5 9. ]]


In [84]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[ 7, 43, 34, 60],
       [ 3, 55, 78, 36],
       [94, 37, 84, 52],
       [33, 79, 12, 18],
       [63, 78, 42, 52]])

In [85]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3

In [101]:
k=arr3.flatten()
k.sort()
k

array([ 3,  7, 12, 18, 33, 34, 36, 37, 42, 43, 52, 52, 55, 60, 63, 78, 78,
       79, 84, 94])

In [97]:
for i in range(len(k)):
 if k[i]>25 or k[i]%3==0:
  print(k[i])

3
12
18
33
34
36
37
42
43
52
52
55
60
63
78
78
79
84
94


In [96]:
print(k[i])

94


In [75]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()

In [106]:
np.percentile(arr3,10)

11.5

In [107]:
np.percentile(arr3,25)

33.75

In [108]:
np.percentile(arr3,50)

47.5