In [130]:
import numpy as np

In [131]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [132]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1

In [133]:
col1=arr1[:,0]
col1

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [134]:
col2=arr1[:,1]
col2

array([ 1,  6, 11, 16, 21, 26, 31, 36])

In [135]:
col3=arr1[:,2]
col3

array([ 2,  7, 12, 17, 22, 27, 32, 37])

In [136]:
col3=arr1[:,3]
col3

array([ 3,  8, 13, 18, 23, 28, 33, 38])

In [137]:
col4=arr1[:,4]
col4

array([ 4,  9, 14, 19, 24, 29, 34, 39])

In [138]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 

In [139]:
arr1


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [140]:
arr1[0:8:3,0:5:2]


array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [141]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 100

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[6241, 4397, 3111, 8060,  835],
       [9163, 1026, 9950, 2548, 7732]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [142]:
# Q3. Write a code to normalize arr2.

In [143]:
x=arr2
 
xmax = x.max()
 
xmin = x.min()
 
xchanged = (x - xmin)/(xmax - xmin)
 
print("After normalization array x = \n", xchanged)

After normalization array x = 
 [[0.59308832 0.39078442 0.2496983  0.79264948 0.        ]
 [0.9136588  0.02095447 1.         0.18793198 0.75666484]]


In [144]:
np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [145]:
# Q4. How would you check if your numpy array has some missing values?

# Hint: Thoda research karo numpy me existing functions hai

In [146]:
import numpy as np
data = np.ma.masked_array(np.arange(10))
data[5] = np.ma.masked 

data[data>6] = np.ma.masked 
init_data = np.arange(10)
data = np.ma.masked_array(init_data, mask=(init_data > 6))

In [147]:
data

masked_array(data=[0, 1, 2, 3, 4, 5, 6, --, --, --],
             mask=[False, False, False, False, False, False, False,  True,
                    True,  True],
       fill_value=999999)

In [148]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [203]:
def nth(n,arr):
    a=np.sort(arr)
    return(a[-n])

In [204]:
arr=np.array([12,15,10,1,0])
n=3
print(nth(n,a))

10


In [205]:
n=1
print(nth(n,a))

15


In [206]:
arr=np.array([12,34,40,7,1,0])

In [207]:
n=2
nth(n,arr)

34

In [208]:
n=3

In [209]:
nth(3,arr)

12